### ISSUE TITLE
Can't start the Gamserver

### ISSUE THREAD

**Issue by dutumentaas** [openPanfu/GameServer#14]
Hello,
when i want to start the gameserver in terminal i become this error:

java- jar gameserver.jar

Exception in thread "main" java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.valueOf(Integer.java:766)
	at org.openpanfu.gameserver.util.Logger.log(Logger.java:30)
	at org.openpanfu.gameserver.util.Logger.error(Logger.java:49)
	at org.openpanfu.gameserver.GameServer.main(GameServer.java:96)

i use mac os x with xampp i have java 8

**Comment by altro50** [comment]
Did you download the gameserver.properties file as well?
Did you use it before on a different update?

**Comment by dutumentaas** [comment]
no

**Comment by altro50** [comment]
You need to download the `gameserver.properties` file and place it in the same directory as `gameserver.jar`.
